DROP TABLE PAPER CASCADE CONSTRAINTS;
DROP TABLE REFERENCE CASCADE CONSTRAINTS;
DROP TABLE AUTHOR CASCADE CONSTRAINTS;
DROP TABLE MAJOR CASCADE CONSTRAINTS;
DROP TABLE WRITE CASCADE CONSTRAINTS;
DROP TABLE JOURNAL CASCADE CONSTRAINTS;
DROP TABLE FIELD CASCADE CONSTRAINTS;
DROP TABLE KEYWORD CASCADE CONSTRAINTS;
DROP TABLE HAS CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE K_BOOKMARK CASCADE CONSTRAINTS;
DROP TABLE A_BOOKMARK CASCADE CONSTRAINTS;
DROP TABLE P_BOOKMARK CASCADE CONSTRAINTS;
DROP TABLE POST CASCADE CONSTRAINTS;
DROP TABLE COMMENTS CASCADE CONSTRAINTS;


